steps:
  # Install dependencies
  - name: Install Python dependencies
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Check import formatting
  - name: Sort Python imports
    entrypoint: python
    args: ["-m", "isort", "--check", "app_backend", "util", "arxiv_lunacy", "scripts"]

  # Check formatting
  - name: Check Python code formatting
    entrypoint: python
    args: ["-m", "black", "--check", "app_backend", "util", "arxiv_lunacy", "scripts"]

  # Check formatting
  - name: Lint Python code
    entrypoint: python
    args: ["-m", "pylint", "app_backend", "util", "arxiv_lunacy", "scripts"]

  # Check typing
  - name: Typecheck Python code
    entrypoint: python
    args: ["-m", "mypy", "app_backend", "util", "arxiv_lunacy", "scripts"]

  # Run tests
  - name: Run Python unit tests
    entrypoint: python
    args: ["-m", "pytest"]

  - name: Switch to frontend
    entrypoint: cd
    args: ["app_frontend"]

  - name: Install JS dependencies
    entrypoint: npm
    args: ["install", "--legacy-peer-deps"]

  - name: Lint Typescript code
    entrypoint: npx
    args: ["eslint" ,"src/*.tsx"]
  
timeout: "1600s"