steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Check import formatting
  - name: python
    entrypoint: python
    args: ["-m", "isort", "--check", "app_backend", "util", "arxiv_lunacy", "scripts"]

  # Check formatting
  - name: python
    entrypoint: python
    args: ["-m", "black", "--check", "app_backend", "util", "arxiv_lunacy", "scripts"]

  # Check formatting
  - name: python
    entrypoint: python
    args: ["-m", "pylint", "app_backend", "util", "arxiv_lunacy", "scripts"]

  # Check typing
  - name: python
    entrypoint: python
    args: ["-m", "mypy", "app_backend", "util", "arxiv_lunacy", "scripts"]

  # Run tests
  - name: python
    entrypoint: python
    args: ["-m", "pytest"]

  - name: bash
    entrypoint: cd
    args: ["app_frontend"]

  - name: npm
    entrypoint: npm
    args: ["install", "--legacy-peer-deps"]

  - name: npm
    entrypoint: npx
    args: ["eslint" ,"src/*.tsx"]
  
timeout: "1600s"